### ISSUE TITLE
BEEFY sync verification

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#41] opened 2021-01-07 16:31 UTC
During the sync process we should verify incoming BEEFY justifications that we get from the peer.
We need to plug into block import pipeline, similar to how GRANDPA is doing that.

**Comment by seunlanlege** [comment] 2021-11-13 14:49
Is it possible that BEEFY replaces Grandpa in the near future?

**Comment by tomusdrw** [comment] 2021-11-26 13:53
> Is it possible that BEEFY replaces Grandpa in the near future?

No. BEEFY augments GRANDPA and requires it to be finalising as well. Thanks to GRANDPA we can be sure that the are no forks, so it's much easier to come to an agreement what to vote on.

**Comment by acatangiu** [comment] 2022-04-01 11:00
Duplicate of https://github.com/paritytech/grandpa-bridge-gadget/issues/183

**Closed by acatangiu** 2022-04-01 11:00 UTC
Labels: enhancement, M-gadget
